find_trending_companies:
  description: >
    Find the top trending companies in the news in {sector} by searching the latest news.
    Always find different companies, not the ones you have already found before.
  expected_output: >
    A list of trending companies in {sector}
  agent: trending_company_finder
  output_files: output/trending_companies.json

research_trending_companies:
  description: >
    Given a list of trending companies, provide detailed analysis of each company in a report by searching online.
  expected_output: >
    A report containing detailed analysis of each company
  agent: financial_reseacher
  context:
    - find_trending_comapnies
  ourput_files: output/research_report.json

